config/routes.rb
Ashanta::Application.routes.draw do
 root :to => 'eventi#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/eventi', to:'eventi#show', as: 'eventis'
  get '/eventi/:id', to: 'eventi#single', as: 'eventi'
  get '/tradizzione', to: 'eventi#tradizzione', as: 'tradizzione'
  get '/istruttore', to: 'eventi#istruttore', as: 'istruttore'
  get '/classi-orari', to: 'eventi#classi', as: 'classi'
  get '/bed-breakfast', to: 'eventi#bed', as: 'bed'
  get '/galleria', to: 'eventi#galleria',as: 'galleria'
  resources :messages, only: [:index, :create]
  match '/contattaci' => 'messages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/eventi.rb
class Eventi < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  attr_accessible :date, :description, :location, :title, :slug

end

app/models/message.rb
# app/models/message.rb
class Message < MailForm::Base
  attribute :name,          :validate => true
  attribute :email,         :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message_title, :validate => true
  attribute :message_body,  :validate => true 

  def headers
    {
      :subject => "Un Mensaje",
      :to => "mijail.rondon@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventi_controller.rb
class EventiController < ApplicationController
def index
	@custitle="Ashanta Yoga Urbino"
	respond_to do |format|
        format.html
    end
end
def show
	@custitle="Yoga Eventis | Ashtanga Yoga Urbino"
	@e=Eventi.page(params[:page]).per(5).order('created_at DESC')
	respond_to do |f|
		f.html
	end
	
end
def single
	@e=Eventi.find(params[:id])
	@custitle="#{@e.title} | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end
def bed
	@custitle="Bed & Breakfast | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end
def tradizzione
	@custitle="Tradizzione | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end
def istruttore
	@custitle="Istruttore | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end
def galleria
	@custitle="Galleria | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end
def classi
	@custitle="Classi e Orari | Ashtanga Yoga Urbino"
	respond_to do |f|
		f.html
	end
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html

  def index
  end

  def create
    message = Message.new(params[:contact_form])
    if message.deliver
      redirect_to root_path, :notice => 'Email has been sent.'
    else
      redirect_to root_path, :notice => 'Email could not be sent.'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventi_helper.rb
module EventiHelper
end

app/views/eventi/bed.html.erb
<h1>Bed & Breakfast</h1>
<div class="row">
  <div class="span5">
    <div id="myCarousel2" class="carousel slide">

  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <img class="img-rounded" src="<%= image_path('vista_frontale.jpg') %>">
      <div class="carousel-caption">
                      <h4>Vista Frontale - Branca Yoga</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('cucina.jpg') %>">
      <div class="carousel-caption">
                      <h4>Cucina</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('soggiorno_1.jpg') %>">
      <div class="carousel-caption">
                      <h4>Soggiorno</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('soggiorno_2.jpg') %>">
      <div class="carousel-caption">
                      <h4>Soggiorno</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('yoga_sala.jpg') %>">
      <div class="carousel-caption">
                      <h4>Yoga Sala</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('cammera_doppia.jpg') %>">
      <div class="carousel-caption">
                      <h4>Cammera Doppia</h4>
      </div>
    </div>
    <div class="item">
      <img class="img-rounded" src="<%= image_path('cammera_tripla.jpg') %>">
      <div class="carousel-caption">
                      <h4>Cammera Tripla</h4>
      </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel2" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel2" data-slide="next">&rsaquo;</a>
</div>
  </div>
  <div class="span7">
    <p>In una piccola collina, chiamata  Il Colle,  da cui si gode la vista dei monti Mondiego e Nerone che si svelano Imponenti di fronte  e del paesino di Piobbico che si adagia tra i due rilievi, sorge in un piccolo Borgo rurale il B&amp;B BrancaYoga. Il  Parco del Monte Nerone e le campagne limitrofe quasi selvaggie e con una bassissima antropizzazione costituiscono il luogo ideale per immergersi nella natura e godere di momenti di relax , di avventura, di sport all’aperto. Innumerevoli percorsi per la mountain bike, falesie molto apprezzate dagli amanti dell’arrampicata sportiva, percorsi speleologici nelle grotte del monte Nerone , trekking attraverso affascinanti  sentieri alla scoperta di antichi mulini, conventi abbandonati, ruderi di castelli . La visita  al Castello Brancaleoni , nell’abitato di Piobbico, ricco di storia e di arte. Ma la specialità del B&amp;B BrancaYoga è la possibilità di coniugare il contesto di cui sopra con la pratica dello Yoga, di cui Sandro Brancaleoni è appassionato e istruttore dal 1999.(Diplomato UISP). Il B&amp;B BrancaYoga in circa 200 mq ha disposizione 2 camere doppie e una tripla, due bagni, un’ampia cucina, un soggiorno e una yogashala  attrezzata per lo yoga . Si affitta il posto letto o l’intera struttura. Inoltre è possibile prenotare oltre all’alloggiamento anche le eventuali lezione di yoga.</p>

<p><strong>Per informazioni e prenotazioni  tel 348 1502714 339 8453868</strong></p>
  </div>
</div>

app/views/eventi/classi.html.erb
<h1>Classi e Orari</h1>
<h3>I corsi si svolgono</h3>
<p>a <strong>URBINO (PU)</strong> presso il Palazzetto dello Sport Mondolce sito in via S.S.Annunziata n.26 , il lunedì dalle
<p>18 alle 19,30(Ashtanga), il mercoledì dalle 18 alle 19,30 ( Ashtanga ); il giovedì dalle 20 alle 21,30 (per principianti).</p>
<p>a <strong>Fermignano (PU)</strong> il lunedì dalle 20 alle 21,30 (Ashtanga), giovedì dalle 18 alle 19,30 (per principianti).</p>
<p>a <strong>Cagli (PU)</strong> presso il centro fitness ECHO CLUB sito in Zona Caldiracci,(Ashtanga ) il venerdì dalle 19 alle 20,30.
<p>a <strong>Rimini</strong>  presso il Centro Gestalt LA STANZA DELL’ANIMA  sito in via Milazzo 9, il martedì dalle 19 alle 20,30 (Ashtanga).
<p>a <strong>Piobbico (PU)</strong> in via Colle n.151  la domenica dalle 10 alle 12 (Ashtanga).
<strong>A richiesta si svolgono lezioni private.</strong></p>

app/views/eventi/contacti.html.erb
<div class="row">
  <div class="span3 separa">
    <h2>Contacti</h2>
  </div>
  <div class="formulario span8">


  <%=
simple_form_for :contact_form, url: '/contacti', :method => :post, :html => {:class => 'form-horizontal' } do |f| %>
  
<div class="control-group">
              <label class="control-label" for="inputEmail">Nombre</label>
              <div class="controls">
                <input class="span6" type="text" id="inputNombre" placeholder="Nombre">
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="inputEmail">Email</label>
              <div class="controls">
                <input class="span6" type="text" id="inputEmail" placeholder="Email">
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="inputEmail">Mensaje</label>
              <div class="controls">
                <textarea class="span6" rows="3"></textarea>
              </div>
            </div>
            <div class="control-group">
              <div class="controls">
               
              
  <%= f.button :submit %>
 <% end %>
  
  </div>
  </div>

  </div>
</div>

app/views/eventi/galleria.html.erb
<h2>Galleria</h2>
<ul id="" class="links thumbnails">

  <li class="span4">
    <a href="<%= image_path('1.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('1_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('2.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('2_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('3.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('3_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('4.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('4_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('5.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('5_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('6.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('6_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('7.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('7_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('8.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('8_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('9.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('9_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('10.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('10_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('11.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('11_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('12.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('12_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('13.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('13_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('14.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('14_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('15.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('15_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('16.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('16_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('17.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('17_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('18.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('18_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('19.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('19_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('20.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('20_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('21.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('21_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('22.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('22_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('23.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('23_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('24.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('24_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('25.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('25_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('26.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('26_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('27.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('27_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('28.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('28_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('29.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('29_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('30.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('30_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('31.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('31_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('32.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('32_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('33.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('33_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('34.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('34_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('35.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('35_p.jpg') %>" />
    </a>
  </li>
  
  <li class="span4">
    <a href="<%= image_path('36.jpg') %>" class="fancybox thumbnail" rel="fancybox-thumb">
    <img src="<%= image_path('36_p.jpg') %>" />
    </a>
  </li>
  
</ul>

app/views/eventi/index.html.erb
<div class="row inicio">
        <div class="span4">
        <a href="<%= url_for(eventis_path) %>"><img class="bloque" src="<%= image_path('event.png') %>" />
          <h2>Eventi</h2></a>
          <p>Abbiamo un numerò di corsi itineranti che potranno variare dipendendo della pianificazione del mese. Entra in “eventi” e potrai vedere le ultime notizie o i cambiamenti di ora, luogo e data delle nostre attività.</p>
        </div>
        <div class="span4">
          <a href="<%= url_for(classi_path) %>"><img class="bloque" src="<%= image_path('yoga.png') %>" />
          <h2>Classi e Orari</h2></a>
          <p>Costantemente stiamo svolgendo lezioni di Yoga a Urbino, Fermignano, Cagli, Rimini e a Piobbico di maniera regolare con orari flessibili alle tue necessità. Entra in Classi e Orari per successiva informazione.</p>
       </div>
        <div class="span4">
          <a href="<%= url_for(bed_path) %>"><img class="bloque" src="<%= image_path('rest.png') %>" />
          <h2>Bed & Breakfast</h2></a>
          <p>Abbiamo a disposizione a tutti i turisti e amanti della natura e del Yoga: B&B BrancaYoga.  Ha a disposizione 2 camere doppie e 1 tripla, due bagni, un’ampia cucina, un soggiorno e una yoga sala  attrezzata per lo yoga. Hai la possibilità perfetta per un weekend  indimenticabile.</p>
        </div>
</div>

app/views/eventi/istruttore.html.erb
<h1>Istruttore</h1>
<div class="row">
  <div class="span5">
    <img class="img-rounded" src="<%= image_path('istruttore.jpg') %>">
  </div>
  <div class="span7">
    <p>Sandro Brancaleoni dal 1990 lavora come Informatore Scientifico del farmaco nella provincia di Pesaro-Urbino e contemporaneamente comincia ad interessarsi e a praticare lo Yoga. Nel 1999 consegue il diploma di istruttore riconosciuto UISP presso la scuola del  M°Bruno Baleotti di Bologna (metodo Parinama) ed inizia ad insegnare. Nel 2000 comincia a praticare l’Asthanga vinyasa Yoga presso Asht. Yoga Research Istitute diretta dal M° Lino Miele, frequentanto da allora costantemente i workshops e i ritiri . Viene autorizzato nel giugno 2011 dal M° Miele ad introdurre l’insegnamento della 1°serie. Nel 2011 interrompe l’attività di Informatore Scientifico per occuparsi a tempo pieno allo Yoga. Nel giugno
2013 partecipa al In-Depth Study of Astanga Yoga, organizzato dal M°Miele in collaborazione con i suoi assistenti dell’AYRI di Roma, conseguendo il diploma all’insegnamento della prima serie.</p>
  </div>
</div>

app/views/eventi/show.html.erb
<h1>Eventi</h1>
<% @e.each do |e| %>
      <div class="row">
        <div class="span4">
        <img class="bloque img-polaroid" src="http://maps.googleapis.com/maps/api/staticmap?center=<%= e.location %>&maptype=roadmap&zoom=17&size=300x200&sensor=true&markers=size:big%7Ccolor:red%7C<%= e.location %>" />
        </div>
        <div class="span8">
          <h2><%= link_to e.title, eventi_path(e) %></h2>
          
          <p><%= e.description %></p>
          
          <span><i class="icon-calendar"></i><%= e.date.strftime("%d/%m/%Y %H:%M %p") %></span>
          <span class="pull-right"><i class="icon-map-marker"></i><%= e.location %></span>
       </div>
      </div>
      <hr />
<% end %>
<%= paginate @e %>

app/views/eventi/single.html.erb
      <div class="row">
        <div class="span4">
        <img class="bloque img-polaroid" src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @e.location %>&maptype=roadmap&zoom=17&size=300x200&sensor=true&markers=size:big%7Ccolor:red%7C<%= @e.location %>" />
        </div>
        <div class="span8">
          <h2><%= @e.title %></h2>
          
          <p><%= @e.description %></p>
          
          <span><i class="icon-calendar"></i><%= @e.date.strftime("%d/%m/%Y %H:%M %p") %></span>
          <span class="pull-right"><i class="icon-map-marker"></i><%= @e.location %></span>
       </div>
      </div>
      <hr />

app/views/eventi/tradizzione.html.erb
<h1>La Tradizzione</h1>
<p>L’Ashtanga yoga trova le sue origini nella tradizione tramandata dal saggio Vamana Rishi (Yoga Korunta) e attraverso  Guru Rama Mohan Brahmachari prima e Krishnamacharya poi arriva fino a Pattabhi Jois (1927). Pattabhi Jois riceve nel 1937 il titolo di Vidwan  e viene nominato professore e capo dipartimento di Yoga del Maharaja Sanskrit College di Mysore.</p>

<p>Nel 1945 viene onorato del titolo di <em>“Yogasana Visharada”</em> . Nel 1948  fonda l ‘ Ashtanga Yoga Research Istitute. Dal 1976 al 1978 è stato professore onorario di Yoga presso il <em>“Goovernament College of Indian Medicine”</em>.</p>

<p>Pattabhi Jois  è stato uno dei grandi Yogi che ha condiviso il suo sapere con studenti di tutto il mondo.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
  <head>
    <title><%= @custitle %></title>
    	<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="ico/favicon.png">
  </head>

  <body>
<div id="blueimp-gallery" class="blueimp-gallery">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li <%= current_page?("/") ? 'class=active' : '' %>><%= link_to "Home", "/"%></li>
              <li <%= current_page?(tradizzione_path) ? 'class=active' : '' %>><%= link_to "La tradizione", tradizzione_path %></li>
              <li <%= current_page?(istruttore_path) ? 'class=active' : '' %>><%= link_to "Istruttore", istruttore_path %></li>
              <li <%= current_page?(classi_path) ? 'class=active' : '' %>><%= link_to "Classi e Orari", classi_path %></li>
              <li <%= current_page?(bed_path) ? 'class=active' : '' %>><%= link_to "Bed & Breakfast", bed_path %></li>
              <li 
              <%=
              	current_page?(eventis_path) ? 'class=active' : '' 
              %>><%= link_to "Eventi", eventis_path %></li>
              <li <%= current_page?(galleria_path) ? 'class=active' : '' %>><%= link_to "Galleria", galleria_path %></li>
              <li <%= current_page?('/contattaci') ? 'class=active' : '' %>><%= link_to "Contattaci", '/contattaci' %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="header">
           <div class="slide-holder"></div>
      <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
    	<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    	<li data-target="#myCarousel" data-slide-to="1"></li>
    	<li data-target="#myCarousel" data-slide-to="2"></li>
  	  </ol>
        <div class="carousel-inner">
            <div class="active item">
            <img src="<%= image_path('banner.png') %>" />
            </div>
            <div class="item"><img src="<%= image_path('banner2.png') %>" /></div>
            <div class="item"><img src="<%= image_path('banner.png') %>" /></div>
        </div>
      </div>     
    </div>
    <div class="container blanco">
    	<% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>

<%= yield %>

    </div> <!-- /container -->
      <div class="footer">
        <div class="container row">
          <div class="span4 barrita">
              <h3>Siti da segnalare</h3>
              <ul class="unstyled">
                <li>
                  <a href="http://www.astanga.it/" target="_blank" >Astanga Yoga Research Institute</a>
                </li>
                <li>
                  <a href="http://www.astangamilano.it/" target="_blank">Ashtanga Yoga Milano</a>
                </li>
                <li>
                  <a href="http://www.hathayoga.it/" target="_blank">Parinama Yoga</a>
                </li>
              </ul>
          </div>
          <div class="span4 barrita">
            <h3>Contattaci</h3>
            <ul class="unstyled">
              <li>(+39) 348-150-2714</li>
              <li>(+39) 339-845-3868</li>
              <li>brancayoga@gmail.com</li>
            </ul>
          </div>
            
        </div>
      </div>
      <div class="creditos">
        <div class="container">
          &copy;2013 Ashtanga Urbino<br />
          Grafica: <a href="http://www.abrahmatansini.com" title="Abrahma Tansini" target="_blank">Abrahma Tansini</a> / Programazione: <a href="http://www.mijailr.com" title="Mijaíl Rondón" target="_blank">Mijaíl Rondón</a>
        </div>
      </div>
    

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for :contact_form, url: messages_path, :method => :post, :html => {:class => 'form-horizontal' } do |f| %>
  
  <%= f.input :name, label: "Nome", :input_html =>{:class => 'span6'} %>
  <%=f.input :email, label: "Email", :input_html =>{:class => 'span6'} %>
  <%=f.input :message_title, label: "Assunto", :input_html =>{:class => 'span6'} %>
  <%=f.input :message_body, label: "Tuo messaggio", as: :text, :input_html => { :rows => 3, :class => 'span6' }%>
  <div class="control-group">
              <div class="controls">
  <%=f.button :submit, value: "Invia messaggio"  %>
  </div>
            </div>
  <% end %>

app/views/messages/index.html.erb
<div class="row">
  <div class="span3 separa">
    <h2>Contattaci</h2>
    <p itemscope="" itemtype="http://schema.org/Organization">
            <strong itemprop="name">Astanga Urbino</strong><br>
            (0039) 348 1502714 <br>
            (0039) 339 8453868 <br>
            brancayoga@gmail.com <br>
    </p>
  </div>
  <div class="formulario span8">
  	<%= render "form" %>
  </div>
</div>